dynamiC: dynamic_string.c File Reference
dynamic_string.c File Reference
Definition of C string manipulation functions.
#include "dynamic_string.h"
Macros
#define FLOAT_DIGITS 100000.
Functions
dyn_ushort dyn_strlen (dyn_const_str str)
Returns the length of an string.
void dyn_strcat (dyn_str destination, dyn_const_str source)
Concatenate strings.
void dyn_strcat2 (dyn_str destination, dyn_const_str source)
Concatenate strings, required memory is automatically allocated.
void dyn_strcpy (dyn_str destination, dyn_const_str source)
Copy string.
dyn_ushort dyn_itoa_len (dyn_int i)
Calculates the number of required characters for integer to string (decimal) conversion, minus increases the value by one.
void dyn_itoa (dyn_str str, dyn_int i)
Integer to ASCII-string conversion.
dyn_ushort dyn_ftoa_len (const dyn_float f)
Calculates the number of required characters for float to string (decimal) conversion, minus increases the value by one.
void dyn_ftoa (dyn_str str, const dyn_float f)
Float to ASCII-string conversion (decimal).
dyn_char dyn_strcmp (dyn_const_str a, dyn_const_str b)
Compares the string a to the string b.
Detailed Description
Definition of C string manipulation functions.
Author
André Dietrich
Date
14 December 2016
Copyright
Copyright 2016 André Dietrich. All rights reserved.
This project is released under the MIT-License.
Definition in file dynamic_string.c.
Function Documentation
dyn_ftoa()
void dyn_ftoa (dyn_str str, const dyn_float f)
Float to ASCII-string conversion (decimal).
The length of the character-array has to be sufficient, it can be calculated previously with function dyn_ftoa_len.
See also
dyn_ftoa_len
dyn_itoa
Parameters
[out] str character array with with new ASCII representation of f
[in] f float value to convert
Definition at line 185 of file dynamic_string.c.
Referenced by dyn_get_bool().
 {
     dyn_int a = (dyn_int) f;
     dyn_int b = (dyn_int) ((f - a) * FLOAT_DIGITS);
     dyn_itoa(str, a);
     dyn_ushort len = dyn_strlen(str);
     str[len] = '.';
     dyn_itoa(&str[len+1], b < 0 ? -b : b);
 }
dyn_ftoa_len()
dyn_ushort dyn_ftoa_len (const dyn_float f)
Calculates the number of required characters for float to string (decimal) conversion, minus increases the value by one.
Parameters
f float value to check
Returns
string length
Definition at line 162 of file dynamic_string.c.
Referenced by dyn_get_bool().
 {
     dyn_ushort len = 1;
     dyn_int a = (dyn_int) f;
     dyn_int b = (dyn_int) ((f - a) * FLOAT_DIGITS);
     len += dyn_itoa_len(a);
     len += dyn_itoa_len(b);
     return len;
 }
dyn_itoa()
void dyn_itoa (dyn_str str, dyn_int i)
Integer to ASCII-string conversion.
The length of the character array has to have a sufficient length, it can be calculated previously with function dyn_itoa_len "(" str ")"
See also
dyn_ftoa
Parameters
[out] str character array with ASCII representation of i
[in] i integer value to convert
Definition at line 140 of file dynamic_string.c.
Referenced by dyn_get_bool().
 {
     char const digit[] = "0123456789";
     if (i<0) {
         *str++ = '-';
         i *= -1;
     }
     str += dyn_itoa_len(i);
     *str = '\0';
     do {
         *--str = digit[i%10];
         i /= 10;
     } while(i);
 }
dyn_itoa_len()
dyn_ushort dyn_itoa_len (dyn_int i)
Calculates the number of required characters for integer to string (decimal) conversion, minus increases the value by one.
Examples:
dyn_itoa_len(0)    == 1
dyn_itoa_len(1)    == 1
dyn_itoa_len(999)  == 3
dyn_itoa_len(-999) == 4
Parameters
i integer value to convert
Returns
length of decimal string
Definition at line 114 of file dynamic_string.c.
Referenced by dyn_get_bool(), and dyn_itoa().
 {
     if (!i) return 1;
     dyn_ushort len = 0;
     if (i < 0) {
         i *= -1;
         ++len;
     }
     while (i)
         i/=10, ++len;
     return len;
 }
dyn_strcat()
void dyn_strcat (dyn_str destination, dyn_const_str source)
Concatenate strings.
Appends a copy of the source string to the destination string. The terminating null character in destination is overwritten by the first character of source, and a null-character is included at the end of the new string formed by the concatenation of both in destination.
destination and source shall not overlap and the length of destination must be sufficient for concatenation, otherwise use dyn_strcat2.
See also
dyn_strcat2
Parameters
destination Pointer to the destination array, which should contain a C string, and be large enough to contain the concatenated resulting string.
source C string to be appended. This should not overlap destination.
Definition at line 54 of file dynamic_string.c.
Referenced by dyn_dict_string_add(), dyn_get_bool(), dyn_list_string_add(), and dyn_strcat2().
 {
     dyn_strcpy(&destination[dyn_strlen(destination)], source);
 }
dyn_strcat2()
void dyn_strcat2 (dyn_str destination, dyn_const_str source)
Concatenate strings, required memory is automatically allocated.
Appends a copy of the source string to the destination string and adds automatically required memory. The terminating null character in destination
is overwritten by the first character of source, and a null-character is included at the end of the new string formed by the concatenation of both in destination.
destination and source shall not overlap.
See also
dyn_strcat
Parameters
destination Pointer to the destination array, which should contain a C string, and be large enough to contain the concatenated resulting string.
source C string to be appended. This should not overlap destination.
Definition at line 76 of file dynamic_string.c.
 {
     destination = (dyn_str) realloc(destination, dyn_strlen(destination)+dyn_strlen(source)+1);
     dyn_strcat(destination, source);
 }
dyn_strcmp()
dyn_char dyn_strcmp (dyn_const_str a, dyn_const_str b)
Compares the string a to the string b.
This function starts comparing the first character of each string. If they are equal to each other, it continues with the following pairs until the characters differ or until a terminating '\0' is reached.
Parameters
a char array to be compared
b char array to be compared
Return values
<0 the first character that does not match has a lower value in a than in b
0 the contents of both strings are equal
>0 the first character that does not match has a greater value in a than in b
Definition at line 212 of file dynamic_string.c.
Referenced by dyn_dict_has_key().
 {
     while (*a == *b++) {
         if (*a++ == 0)
             return 0;
     }
     return (*a - *(b - 1));
 }
dyn_strcpy()
void dyn_strcpy (dyn_str destination, dyn_const_str source)
Copy string.
Copies the C string pointed by source into the array pointed by destination, including the terminating null character (and stopping at that point).
To avoid overflows, the size of the array pointed by destination shall be long enough to contain the same C string as source (including the terminating null character), and should not overlap in memory with source.
Parameters
[out] destination Pointer to the destination array where the content is to be copied.
[in] source C string to be copied.
Definition at line 94 of file dynamic_string.c.
Referenced by dyn_set_string(), and dyn_strcat().
 {
     while(*source)
         *destination++=*source++;
     *destination = '\0';
 }
dyn_strlen()
dyn_ushort dyn_strlen (dyn_const_str str)
Returns the length of an string.
Iteratates through an character array to sum up its length, the end is defined by the character '\0'.
Parameters
str Pointer to an character array
Returns
string length
Definition at line 27 of file dynamic_string.c.
Referenced by dyn_dict_string_add(), dyn_dict_string_len(), dyn_get_bool(), dyn_list_string_add(), dyn_set_string(), dyn_size(), dyn_strcat(), and dyn_strcat2().
 {
     dyn_ushort len = 0;
     while (*str++)
         ++len;
     return len;
 }