dynamiC: dynamic_op.c File Reference
dynamic_op.c File Reference
Implementation of dynamiC operations module.
#include "dynamic.h"
Macros
#define max_type(A, B) (DYN_TYPE(A) > DYN_TYPE(B)) ? DYN_TYPE(A) : DYN_TYPE(B)
#define CHECK_COPY_REFERENCE(X1)
#define CHECK_NOCOPY_REFERENCE(X2)
#define CHECK_REFERENCE(X1, X2)
Functions
trilean dyn_op_neg (dyn_c *dyn)
Negate dynamic value in param dyn.
trilean dyn_op_add (dyn_c *dyn1, dyn_c *dyn2)
Add dyn2 to dyn1.
trilean dyn_op_sub (dyn_c *dyn1, dyn_c *dyn2)
Subtract dyn2 from dyn1.
trilean dyn_op_mul (dyn_c *dyn1, dyn_c *dyn2)
Multiply dyn1 with dyn2.
trilean dyn_op_div (dyn_c *dyn1, dyn_c *dyn2)
Divide dyn1 by dyn2.
trilean dyn_op_mod (dyn_c *dyn1, dyn_c *dyn2)
dyn1 Modulo dyn2
float fast_approx_pow (float x, float p)
Power function approximation x^y.
trilean dyn_op_pow (dyn_c *dyn1, dyn_c *dyn2)
dyn1 to the power of dyn2
trilean dyn_get_bool_3 (const dyn_c *dyn)
Returns the trinary truth value (DYN_TRUE|DYN_FALSE|DYN_NONE) of an element.
trilean dyn_op_and (dyn_c *dyn1, dyn_c *dyn2)
Logical (trinary) AND operation.
trilean dyn_op_or (dyn_c *dyn1, dyn_c *dyn2)
Logical (trinary) OR operation.
trilean dyn_op_xor (dyn_c *dyn1, dyn_c *dyn2)
Logical (trinary) XOR operation.
trilean dyn_op_not (dyn_c *dyn)
Logical (trinary) Negation.
dyn_char dyn_op_cmp (dyn_c *dyn1, dyn_c *dyn2)
Common compare function for dynamic elements.
trilean dyn_op_id (dyn_c *dyn1, dyn_c *dyn2)
Type and Value Equality.
trilean dyn_op_eq (dyn_c *dyn1, dyn_c *dyn2)
Relational Equality.
trilean dyn_op_ne (dyn_c *dyn1, dyn_c *dyn2)
Relational Not Equal.
trilean dyn_op_lt (dyn_c *dyn1, dyn_c *dyn2)
Relational Less Than.
trilean dyn_op_ge (dyn_c *dyn1, dyn_c *dyn2)
Relational Greater Than or Equal.
trilean dyn_op_gt (dyn_c *dyn1, dyn_c *dyn2)
Relational Greater Than.
trilean dyn_op_le (dyn_c *dyn1, dyn_c *dyn2)
Relational Less Than or Equal.
trilean dyn_op_in (dyn_c *element, dyn_c *container)
Check if dyn2 is element of dyn1.
trilean dyn_op_b_not (dyn_c *dyn)
Binary complement.
trilean dyn_op_b_and (dyn_c *dyn1, dyn_c *dyn2)
Binary AND.
trilean dyn_op_b_or (dyn_c *dyn1, dyn_c *dyn2)
Binary OR.
trilean dyn_op_b_xor (dyn_c *dyn1, dyn_c *dyn2)
Binary XOR.
trilean dyn_op_b_shift_l (dyn_c *dyn1, dyn_c *dyn2)
Binary shift left.
trilean dyn_op_b_shift_r (dyn_c *dyn1, dyn_c *dyn2)
Binary shift right.
Detailed Description
Implementation of dynamiC operations module.
Author
André Dietrich
Date
14 December 2016
Copyright
Copyright 2016 André Dietrich. All rights reserved.
This project is released under the MIT-License.
Definition in file dynamic_op.c.
Macro Definition Documentation
CHECK_COPY_REFERENCE
#define CHECK_COPY_REFERENCE (X1)
Value:
if (DYN_TYPE(X1) == REFERENCE2)     \
        DYN_TYPE(X1) = REFERENCE;       \
    if(DYN_TYPE(X1) == REFERENCE)       \
        dyn_copy(X1->data.ref, X1);     \
Definition at line 19 of file dynamic_op.c.
CHECK_NOCOPY_REFERENCE
#define CHECK_NOCOPY_REFERENCE (X2)
Value:
if(DYN_IS_REFERENCE(X2))            \
        X2=X2->data.ref;                \
Definition at line 25 of file dynamic_op.c.
CHECK_REFERENCE
#define CHECK_REFERENCE (X1, X2)
Value:
CHECK_COPY_REFERENCE(X1)            \
    CHECK_NOCOPY_REFERENCE(X2)
Definition at line 30 of file dynamic_op.c.
Function Documentation
dyn_op_cmp()
dyn_char dyn_op_cmp (dyn_c * dyn1, dyn_c * dyn2)
Common compare function for dynamic elements.
Basic compare function for dynamic data dypes, based on the relation between the input parameters, different values are returned, see the list below.
Parameters
dyn1 first dynamic parameter
dyn2 second dynamic parameter
Return values
0 if dyn1 == dyn2
1 if dyn1 < dyn2
2 if dyn1 > dyn2
3 if dyn1 != dyn2
4 if not comparable due to different data types (STRING <= SET)
Definition at line 683 of file dynamic_op.c.
Referenced by dyn_op_eq(), dyn_op_gt(), dyn_op_lt(), and dyn_op_ne().
 {
     enum{EQ,LT,GT,NEQ,TYPE,MARK};//0,1,2,3,4
     dyn_c  *tmp = DYN_IS_REFERENCE(dyn1) ? dyn1->data.ref : dyn1;
     dyn_char ret;
     dyn_c tmp2;
     DYN_INIT(&tmp2);
     dyn_ushort i;
     if(DYN_IS_REFERENCE(dyn2))
         dyn2=dyn2->data.ref;
     if (DYN_IS_NONE(tmp) && DYN_IS_NONE(dyn2))
         goto GOTO_EQ;
     if (DYN_IS_NONE(tmp) && DYN_NOT_NONE(dyn2))
         goto GOTO_LT;
     if (DYN_NOT_NONE(tmp) && DYN_IS_NONE(dyn2))
         goto GOTO_GT;
     //this switch has no breaks goto is used to leave to desired return
     switch (max_type(tmp, dyn2)) {
         case BOOL:
             if (dyn_get_bool(tmp) < dyn_get_bool(dyn2))
                 goto GOTO_LT;
             if (dyn_get_bool(tmp) > dyn_get_bool(dyn2))
                 goto GOTO_GT;
             goto GOTO_EQ;
         case INTEGER:
             if (dyn_get_int(tmp) < dyn_get_int(dyn2))
                 goto GOTO_LT;
             if (dyn_get_int(tmp) > dyn_get_int(dyn2))
                 goto GOTO_GT;
             goto GOTO_EQ;
         case FLOAT:
             if (dyn_get_float(tmp) < dyn_get_float(dyn2))
                 goto GOTO_LT;
             if (dyn_get_float(tmp) > dyn_get_float(dyn2))
                 goto GOTO_GT;
             goto GOTO_EQ;
         case STRING: {
             if (DYN_TYPE(tmp) != DYN_TYPE(dyn2))
                 goto GOTO_TYPE;
             //i = dyn_strcmp(tmp->data.str, dyn2->data.str);
             //if (i < 0)
             ret = dyn_strcmp(tmp->data.str, dyn2->data.str);
             if (ret < 0)
                 goto GOTO_LT;
             //if (i > 0)
             if (ret > 0)
                 goto GOTO_GT;
             goto GOTO_EQ;
         }
         case SET: {
             if (DYN_TYPE(tmp) != DYN_TYPE(dyn2))
                 goto GOTO_TYPE;
             {
                 dyn_c * lset = NULL;
                 dyn_c * rset;
                 if (DYN_LIST_LEN(tmp) == DYN_LIST_LEN(dyn2)){
                     // list might be EQ
                     ret = EQ;
                     lset = tmp;
                     rset = dyn2;
                 } else if (DYN_LIST_LEN(tmp) < DYN_LIST_LEN(dyn2)) {
                     // list might be EQ
                     ret = LT;
                     lset = tmp;
                     rset = dyn2;
                 } else /*if (DYN_LIST_LEN(tmp) > DYN_LIST_LEN(dyn2)) */{
                     // list might be GT
                     ret = GT;
                     lset = dyn2;
                     rset = tmp;
                 }
                 //check if all elements of lset are in rset
                 //break to NEQ or complete to confirm
                 for (i=0; i<DYN_LIST_LEN(lset); ++i) {
                     dyn_set_ref(&tmp2, DYN_LIST_GET_REF(lset, i));
                     dyn_op_in(&tmp2, rset);
                     if (!dyn_get_bool(&tmp2)){
                         ret = NEQ;
                         break;
                     }
                 }
                 goto GOTO_RET;
             }
             //unreachable
         }
         case LIST: {
             if (DYN_TYPE(tmp) != DYN_TYPE(dyn2))
                 goto GOTO_TYPE;
             if (DYN_LIST_LEN(tmp) < DYN_LIST_LEN(dyn2))
                 goto GOTO_LT;
             if (DYN_LIST_LEN(tmp) > DYN_LIST_LEN(dyn2))
                 goto GOTO_GT;
             if (DYN_LIST_LEN(tmp) == DYN_LIST_LEN(dyn2)) {
                 if (DYN_LIST_LEN(tmp) == 0)
                     goto GOTO_EQ;
                 //put marker into return value
                 ret = MARK;
                 for (i=0; i<DYN_LIST_LEN(tmp); ++i) {
                     dyn_set_ref(&tmp2, DYN_LIST_GET_REF(tmp, i));
                     ret = dyn_op_cmp(&tmp2, DYN_LIST_GET_REF(dyn2, i));
                     if (ret != EQ)
                         break;
                 }
                 //reached the end of the for loop
                 goto GOTO_RET;
             }
             //unreachable
         }
     }
     //unreachable
     // break with diffent type (string, list and set)
     goto GOTO_TYPE;
 GOTO_TYPE:
     ret = TYPE;
     goto GOTO_RET;
 GOTO_EQ:
     ret = EQ;
     goto GOTO_RET;
 GOTO_LT:
     ret = LT;
     goto GOTO_RET;
 GOTO_GT:
     ret = GT;
     goto GOTO_RET;
 /*
 GOTO_NEQ:
     ret = NEQ;
     goto GOTO_RET;
 */
 GOTO_RET:
     //dyn_set_int(dyn1, ret);
     return ret;
 }
fast_approx_pow()
float fast_approx_pow (float x, float p)
Power function approximation x^y.
This implementation is based on the fastapprox library of Paul Minero.
See also
https://code.google.com/archive/p/fastapprox/
http://www.machinedlearnings.com/2011/06/fast-approximate-logarithm-exponential.html
Parameters
x base value
y exponential value
approx. float value
Definition at line 417 of file dynamic_op.c.
 {
     union { float f;
             unsigned int i;
     } vx = { x };
     union { unsigned int i;
             float f;
     } mx = { (vx.i & 0x007FFFFF) | 0x3f000000 };
     x = vx.i * 1.1920928955078125e-7f
         - 124.22551499f
         - 1.498030302f * mx.f
         - 1.72587999f / (0.3520887068f + mx.f);
     x *= p;
     float offset = (x < 0) ? 1.0f : 0.0f;
     float clipp = (x < -126) ? -126.0f : x;
     float z = clipp - (int) clipp + offset;
     mx.i =  (unsigned int) ( (1 << 23) * (clipp + 121.2740575f + 27.7280233f / (4.84252568f - z) - 1.49012907f * z) );
     return mx.f;
 }