dynamiC: DynamicList
DynamicList
All list related functions.
Macros
#define DYN_SET_LIST(dyn) dyn_set_list_len(dyn, LIST_DEFAULT)
Initialize dyn as list with default length.
#define DYN_LIST_LEN(dyn) (dyn)->data.list->length
Return list length.
#define DYN_LIST_GET_REF(dyn, i) &(dyn)->data.list->container[i]
Return the reference to the ith element within a dynamic list.
#define DYN_LIST_GET_END(dyn) &(dyn)->data.list->container[DYN_LIST_LEN(dyn)-1]
Return the reference to the last element within a list.
#define DYN_LIST_GET_REF_END(dyn, i) &(dyn)->data.list->container[DYN_LIST_LEN(dyn)-i]
Return the reference to the ith element starting from the last.
Functions
trilean dyn_set_list_len (dyn_c *dyn, dyn_ushort len)
Set dynamic element to list with maximal length.
dyn_c * dyn_list_push (dyn_c *list, dyn_c *element)
Push new element to the end of a list.
dyn_c * dyn_list_push_none (dyn_c *list)
Push NONE element to the end of a list.
trilean dyn_list_pop (dyn_c *list, dyn_c *element)
Pop the last element from the list and move it to param element.
trilean dyn_list_get (dyn_c *list, dyn_c *element, dyn_short i)
Copy the ith element of a list to param element.
dyn_c * dyn_list_get_ref (dyn_c *list, dyn_short i)
Return a reference to the ith element within list, negative values are allowed.
trilean dyn_list_popi (dyn_c *list, dyn_short i)
Pop i elements from the end of a list.
void dyn_list_free (dyn_c *list)
Free the allocated memory of the entire list and set it to NONE.
trilean dyn_list_copy (dyn_c *list, dyn_c *copy)
Make a deep copy of the entire list.
trilean dyn_list_remove (dyn_c *list, dyn_ushort i)
Delete the ith element from a list.
trilean dyn_list_insert (dyn_c *list, dyn_c *element, dyn_ushort i)
Insert a new element at the ith position into a list.
trilean dyn_list_resize (dyn_c *list, dyn_ushort size)
Change the maximal space of a list.
dyn_ushort dyn_list_string_len (dyn_c *list)
Return the length of the string representation of a list.
void dyn_list_string_add (dyn_c *list, dyn_str str)
Add string representation of a list to str.
Detailed Description
All list related functions.
Function Documentation
trilean dyn_list_copy (dyn_c * list, dyn_c * copy)
Make a deep copy of the entire list.
See also
dyn_copy
Parameters
[in] list original
[in,out] copy new list
Return values
DYN_TRUE if the element was found and coppied
DYN_FALSE otherwise
Definition at line 289 of file dynamic_list.c.
Referenced by dyn_get_bool().
 {
     dyn_ushort len = DYN_LIST_LEN(list);
     if (dyn_set_list_len(copy, len)) {
         list = list->data.list->container;
         while (len--) {
             if (!dyn_list_push(copy, list++)) {
                 dyn_free(copy);
                 return DYN_FALSE;
             }
         }
         return DYN_TRUE;
     }
     return DYN_FALSE;
 }
void dyn_list_free (dyn_c * list)
Free the allocated memory of the entire list and set it to NONE.
Parameters
[in,out] list input put has to be a list
Definition at line 53 of file dynamic_list.c.
Referenced by dyn_free().
 {
     dyn_ushort len = DYN_LIST_LEN(list);
     // free all elements within the allocated container element
     dyn_c *ptr = list->data.list->container;
     while (len--) {
         dyn_free(ptr++);
     }
     free(list->data.list->container);
     free(list->data.list);
 }
trilean dyn_list_get (dyn_c * list, dyn_c * element, dyn_short i)
Copy the ith element of a list to param element.
Copies the i value in the list to element. If the i value is negative, then the i value is relative to the last value (-1). If only the reference to the value in the list is required, use dyn_list_get_ref
See also
dyn_list_get_ref
Parameters
[in] list input has to be of type LIST
[in,out] element to copy to
[in] i position in list
Return values
DYN_TRUE if the element was found and coppied
DYN_FALSE otherwise
Definition at line 243 of file dynamic_list.c.
 {
     dyn_free(element);
     dyn_short len = DYN_LIST_LEN(list);
     if (i >= 0) {
         if (i <= len) {
             return dyn_copy(&list->data.list->container[ i ], element);
         }
     } else if ( -i <= len ) {
         return dyn_copy(&list->data.list->container[ len+i ], element);
     }
     return DYN_FALSE;
 }
dyn_c* dyn_list_get_ref (dyn_c * list, dyn_short i)
Return a reference to the ith element within list, negative values are allowed.
Returns the reference of the i value in list, if a negative position value is used, then the position is calculated from the end. And if the i position exceeds the length of the list, NULL is returned.
See also
dyn_list_get
Parameters
list input has to be of type LIST
i position in list
Returns
reference to the ith value
Definition at line 271 of file dynamic_list.c.
Referenced by dyn_dict_get_i_ref().
 {
     if (i >= 0 && i<=DYN_LIST_LEN(list))
         return &list->data.list->container[i];
     else if (i < 0 && -i <= DYN_LIST_LEN(list))
         return &list->data.list->container[ DYN_LIST_LEN(list)+i ];
     return NULL;
 }
trilean dyn_list_insert (dyn_c * list, dyn_c * element, dyn_ushort i)
Insert a new element at the ith position into a list.
Insert a new element at position i to a list, all other elements with pos>i are shifted "to the left" befor the element gets inserted (moved).
 // pseudo code
 dyn_list_insert([0,1,3,4], "22", 2) == [0,1,"22",3,4]
Parameters
[in,out] list input has to be of type LIST
[in] element to be inserted
[in] i position
Return values
DYN_TRUE if the required memory could be allocated
Definition at line 182 of file dynamic_list.c.
Referenced by dyn_op_add().
 {
     dyn_ushort n = DYN_LIST_LEN(list);
     if (n >= i) {
         dyn_list_push_none(list);
         ++n;
         while(--n > i) {
             dyn_move(DYN_LIST_GET_REF(list, n-1), DYN_LIST_GET_REF(list, n));
         }
         dyn_move(element, DYN_LIST_GET_REF(list, i));
     }
     return DYN_TRUE;
 }
trilean dyn_list_pop (dyn_c * list, dyn_c * element)
Pop the last element from the list and move it to param element.
Pops the last element from the list and moves its content to parameter element. The length of the list decreases by one.
Parameters
[in,out] list input has to be of type LIST
[in,out] element where last dynamic value is moved to
Return values
DYN_TRUE if worked properly
Definition at line 205 of file dynamic_list.c.
 {
     dyn_move(DYN_LIST_GET_END(list), element);
     list->data.list->length--;
     if (LST_SPACE(list) - DYN_LIST_LEN(list) > LIST_DEFAULT)
         if (!dyn_list_resize(list, list->data.list->space - LIST_DEFAULT))
             return DYN_FALSE;
     return DYN_TRUE;
 }
trilean dyn_list_popi (dyn_c * list, dyn_short i)
Pop i elements from the end of a list.
Parameters
[in,out] list input has to be of type LIST
[in] i number of elements to be popped
Definition at line 221 of file dynamic_list.c.
Referenced by dyn_list_remove().
 {
     while(i--)
         dyn_free(&list->data.list->container[ --list->data.list->length ]);
     return DYN_TRUE;
 }
dyn_c* dyn_list_push (dyn_c * list, dyn_c * element)
Push new element to the end of a list.
Pushes (copies) an additional element to the end of a list and increases the length value by one. If the maximal available space is reached, then new memory is allocated and the maximal space value gets increased, this additional size value is defined in LIST_DEFAULT.
Parameters
[in,out] list input has to be of type LIST
[in] element to be pushed
Returns
a reference to the element at the end of the list
Definition at line 110 of file dynamic_list.c.
Referenced by dyn_list_copy(), dyn_op_add(), dyn_op_mul(), and dyn_set_insert().
 {
     if (DYN_LIST_LEN(list) == LST_SPACE(list))
         if (!dyn_list_resize(list, list->data.list->space + LIST_DEFAULT))
             return NULL;
     dyn_copy(element, &list->data.list->container[ list->data.list->length++ ]);
     return &list->data.list->container[ list->data.list->length-1 ];
 }
dyn_c* dyn_list_push_none (dyn_c * list)
Push NONE element to the end of a list.
Increses the length value of the list by one and returns a reference to the last NONE element of the list. This reference can be used to move a larger element to the end of a list, without copying.
Parameters
[in,out] list input has to be of type LIST
Returns
reference to the pushed NONE value
Definition at line 130 of file dynamic_list.c.
Referenced by dyn_list_insert().
 {
     if (DYN_LIST_LEN(list) == LST_SPACE(list))
         if (!dyn_list_resize(list, list->data.list->space + LIST_DEFAULT))
             return NULL;
     return &list->data.list->container[ list->data.list->length++ ];
 }
trilean dyn_list_remove (dyn_c * list, dyn_ushort i)
Delete the ith element from a list.
Delete an element from the list at position i, successive elements are moved to close this gap. This function can be interpeted as the opposite to dyp_list_insert
 // pseudo code
 dyn_list_remove([0,1,2,3,4], 2) == [0,1,3,4]
Parameters
[in,out] list input has to be of type LIST
[in] i position to remove
Return values
DYN_TRUE if the required memory could be allocated
DYN_FALSE otherwise
Definition at line 155 of file dynamic_list.c.
Referenced by dyn_op_sub().
 {
     if (DYN_LIST_LEN(list) > i) {
         for(;i<DYN_LIST_LEN(list)-1; ++i) {
             dyn_move(DYN_LIST_GET_REF(list, i+1),
                      DYN_LIST_GET_REF(list, i));
         }
         dyn_list_popi(list, 1);
     }
     return DYN_TRUE;
 }
trilean dyn_list_resize (dyn_c * list, dyn_ushort size)
Change the maximal space of a list.
Resize the maximal usable space, if the size decreases then the removed elements have to be removed previously.
Parameters
[in,out] list input put has to be a list
[in] size new maximal available space
Return values
DYN_TRUE if the required memory could be allocated
DYN_FALSE otherwise
Definition at line 77 of file dynamic_list.c.
Referenced by dyn_dict_resize(), dyn_list_pop(), dyn_list_push(), dyn_list_push_none(), and dyn_op_mul().
 {
     dyn_ushort i;
 //    dyn_ushort len = dyn_length(list);
     dyn_c* new_list = (dyn_c*) realloc(list->data.list->container, size * sizeof(dyn_c));
     if (new_list) {
         list->data.list->container = new_list;
         if (list->data.list->space < size) {
             for(i=DYN_LIST_LEN(list); i<size; ++i)
                 DYN_INIT(&list->data.list->container[i]);
         }
         list->data.list->space = size;
         return DYN_TRUE;
     }
     return DYN_FALSE;
 }
void dyn_list_string_add (dyn_c * list, dyn_str str)
Add string representation of a list to str.
Generates a string representation of the list and all included element, segregated by commas, and attaches it to the end of the string.
Parameters
[in] list input has to be of type LIST
[in,out] str with added list representation
Definition at line 332 of file dynamic_list.c.
Referenced by dyn_get_bool().
 {
     dyn_strcat(str, (dyn_str)"[");
     dyn_ushort len = DYN_LIST_LEN(list);
     if (len == 0) {
         dyn_strcat(str, (dyn_str)"]");
         return;
     }
     dyn_ushort i;
     for (i=0; i<len; i++) {
         dyn_string_add(DYN_LIST_GET_REF(list, i), str);
         dyn_strcat(str, (dyn_str)",");
     }
     str[dyn_strlen(str)-1] = ']';
 }
dyn_ushort dyn_list_string_len (dyn_c * list)
Return the length of the string representation of a list.
The length of the list string representation is calculated by the length of all included elemens plus 2 brackets and the number of commas.
Parameters
list input has to be of type LIST
Returns
length of string
Definition at line 314 of file dynamic_list.c.
Referenced by dyn_get_bool().
 {
     dyn_ushort size = DYN_LIST_LEN(list)+1;
     dyn_ushort len = 2 + size;
     while (--size)
         len += dyn_string_len(DYN_LIST_GET_REF(list, size-1));
     return len;
 }
trilean dyn_set_list_len (dyn_c * dyn, dyn_ushort len)
Set dynamic element to list with maximal length.
Takes in any kind of dynamic paramter, frees all allocated memory and allocates a new array of dynamic elemens with a length defined in paramter len. The len paramter us used to denote the max space available space, initially the lenght of a list is marked as empty. Every application of of dyn_list_push increases the internal counter of dyn->data.list->len, until the max value dyn->data.list->space is reached, if so, new memory is allocated automatically. Every popped value by applying dyn_list_pop decreases the internal counter.
Parameters
[in,out] dyn input any, output LIST
[in] len
Return values
DYN_TRUE if the required memory could be allocated
DYN_FALSE otherwise
Definition at line 23 of file dynamic_list.c.
Referenced by dyn_list_copy(), dyn_op_mul(), dyn_set_dict(), and dyn_set_set_len().
 {
     dyn_free(dyn);
     dyn->data.list = (dyn_list*) malloc(sizeof(dyn_list));
     if (dyn->data.list) {
         dyn->data.list->container = (dyn_c*) malloc(len * sizeof(dyn_c));
         if (dyn->data.list->container) {
             dyn->type = LIST;
             dyn->data.list->space = len;
             dyn->data.list->length = 0;
             // Initialize all elements in list with NONE
             while (len--)
                 DYN_INIT(&dyn->data.list->container[len]);
             return DYN_TRUE;
         }
         free(dyn->data.list);
     }
     return DYN_FALSE;
 }